version: '2'
services:
  nginx-proxy:
    image: nginx
    restart: always
    container_name: nginx-proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/srv/services/shared/certs:/etc/nginx/certs:ro"
    networks:
      - proxy-tier
  nginx-gen:
    image: jwilder/docker-gen
    restart: always
    container_name: nginx-gen
    volumes_from:
      - nginx-proxy
    volumes:
      - ~/projects/nginx-proxy/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    container_name: letsencrypt-nginx-proxy-companion
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    volumes_from:
      - nginx-proxy
    volumes:
      - /srv/services/shared/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier

  nginx-proxy-metrics:
    image: lukaskroepfl/nginx-proxy-metrics
    depends_on:
      - monitoring-influx-db
      - nginx-proxy
    restart: always
    container_name: nginx-proxy-metrics
    environment:
      - PROXY_CONTAINER_NAME=nginx-proxy
      - INFLUX_URL=http://monitoring-influxdb-db:8086
      - INFLUX_DB_NAME=monitoring
      - INFLUX_DB_RETENTION_DURATION=52w
      - INFLUX_DB_TAG_INSTANCE=my-instance
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /~nginx-proxy-metrics/data/GeoLite2-City.mmdb:/GeoLite2-City.mmdb:ro
    networks:
      - proxy-tier

  monitoring-influx-db:
    image: influxdb:alpine
    restart: always
    container_name: monitoring-influxdb-db
    volumes:
      - "~/monitoring-influxdb-db/data:/var/lib/influxdb"
    networks:
      - proxy-tier

  monitoring-grafana:
    image: grafana/grafana
    restart: always
    container_name: monitoring-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_ROOT_URL=http://localhost
      - GF_SECURITY_ADMIN_PASSWORD=your_password
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external:
      name: proxy_tier
