# This workflow will release
name: Release

on:
  workflow_run:
    workflows: [ "xLatest Build" ]
    branches: [ main ]
    types:
      - completed

jobs:

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build Go
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./.build/main ./cmd

      - name: Test Go
        run: go test -v ./...

      - name: Build and push latest image
        run: |
          docker login --username pommes --password ${{ secrets.GHCR_IMAGE_REGISTRY_SECRET }} ghcr.io
          docker build . --tag ghcr.io/pommes/nginx-proxy-metrics:latest
          docker push ghcr.io/pommes/nginx-proxy-metrics:latest




    
    
